---
configRev: 1
longmynd:
    binpath: /home/pi/longmynd/longmynd
    mediapath: /home/pi/lmmedia
    statuspath: /home/pi/lmstatus

default:
    freq: 741500
    sr:   1500
    pol:  NONE
    port: TOP

ir:
    repeatFirst: 200
    repeatDelay: 100
    repeatReset: 400
    libraryPath: /home/pi/RydeHandsets/definitions
    handsets:
        - virgin

gpio:
    repeatFirst: 200
    repeatDelay: 100
    rxGood: 4
    buttons:
        POWER:  16
        UP:     14
        DOWN:   27
        LEFT:   22
        RIGHT:  23
        SELECT: 24
        BACK:   25
        MENU:   5
        MUTE:   6

debug:
    autoplay: True
    disableHardwareCodec: True

